repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v3.2.0
    hooks:
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: requirements-txt-fixer
      - id: check-json
      - id: check-merge-conflict
#      - id: trailing-whitespace
#  - repo: 'https://github.com/pycqa/flake8'
#    rev: 4.0.1
#    hooks:
#      - id: flake8
#  - repo: 'https://github.com/psf/black'
#    rev: 20.8b1
#    hooks:
#      - id: black
#        args:
#          - '--config=pyproject.toml'
  - repo: 'https://github.com/hadialqattan/pycln'
    rev: v0.0.1-beta.3
    hooks:
      - id: pycln
        args:
          - '--config=pyproject.toml'
  - repo: 'https://github.com/pycqa/isort'
    rev: 5.5.4
    hooks:
      - id: isort
        files: \.(py)$
        args:
          - '--settings-path=pyproject.toml'
#  - repo: 'https://github.com/jorisroovers/gitlint'
#    rev:  ""
#    hooks:
#      - id: gitlint
#        args:
#          - '--contrib=CT1'
#          - '--msg-filename'
