global:
  scrape_interval: 15s # when Prometheus is pulling data from exporters etc
  evaluation_interval: 30s # time between each evaluation of Prometheus' alerting rules

scrape_configs:
  - job_name: Setup-Grafana-with-Prometheus-for-Python-projects-using-Docker   # your project name
    static_configs:
      - targets:
        - app:8000